#pragma once

#include "Camera_Free.h"
#include "Terrain.h"
#include "Model.h"
#include "LoadModel.h"

#include "Player.h"
#include "Player_LevelBoss.h"
#include "Player_Basic.h"
#include "Player_BlueEye.h"
#include "Player_SR.h"
#include "Player_Pistol.h"
#include "Player_Body.h"
#include "Player_Bullet.h"
#include "Player_BlueBullet.h"
#include "Player_Skill.h"
#include "Camera_Player.h"

#include "Player_Effect_Flame.h"
#include "Player_Effect_Dash.h"
#include "Player_posion.h"

#include "Monster_Boom.h"
#include "Monster_BoomPart.h"
#include "Monster_Arrow.h"
#include "Monster_Sword.h"
#include "Monster_ShieldMan.h"
#include "Monster_ShieldManPart.h"
#include "Monster_Effect.h"
#include "Arrow.h"

#include "Boss.h"
#include "Boss_65_Body.h"
#include "Boss_Skill_Shot.h"
#include "Boss_Skill_JumpStone.h"
#include "Boss_Skill_ThrowStone.h"
#include "Boss_Effect_Crack.h"
#include "Boss_Effect_CrackLight.h"
#include "Boss_Effect_TargetRing.h"

#include "Map_Stage1.h"
#include "Map_Stage1_Boss.h"
#include "Door.h"
#include "MiniDoor.h"
#include "Coin.h"
#include "Box.h"
#include "BoxPart.h"
#include "Sky.h"

#include "NextPortal.h"
#include "Effect_Common.h"
#include "Particle_Explosion.h"
#include "Particle_BoxOpen.h"
#include "Particle_BossLevel.h"

#include "UI_Common.h"
#include "UI_PlayerIcon.h"
#include "UI_PlayerHPBar.h"
#include "UI_PlayerShieldBar.h"
#include "UI_IconBg.h"
#include "UI_Com_Number.h"
#include "UI_MiniMap.h"
#include "UI_MiniMap_Player.h"
#include "UI_MiniMap_Monster.h"
#include "UI_PlayerWeapon_Img.h"
#include "UI_PlayerWeapon_SkillbgMid.h"
#include "UI_PlayerWeapon_SkillbgR.h"
#include "UI_PlayerDamaged.h"
#include "UI_Boss65ShieldBar.h"
#include "UI_Boss65HPBar.h"
#include "UI_TextNum.h"
#include "UI_CoinCnt.h"
#include "UI_Player_Restart.h"
#include "UI_Etc_NextStage.h"
#include "UI_Etc_OpenBox.h"
#include "UI_Etc_BoxItem.h"
#include "UI_Etc_BoxItems.h"
#include "UI_Etc_BoxItemsBg.h"
#include "UI_Victory.h"

#include "Obj_Common.h"

#include "io.h"
#include <json/nlohmann/json.hpp>

using json = nlohmann::json;
